### ISSUE TITLE
Can't access data from Ecowitt-WH51 soil sensor

### ISSUE THREAD

**Issue by sbbe** [DanielWinks/HassOS-Addons#13]
Hey! I have first commented my issue at #5, but thought I'd make a new issue so it's cleaner. I have an Ecowitt (Fineoffset) WH51, which has also an id, but not an uid or channel. I can provide a screenshot from MQTT Explorer with all published outputs. 
![MQTT_Explorer_kUebjQT1ex](https://user-images.githubusercontent.com/68023011/174284832-b98d5a6c-a39e-4e10-8023-e133e387f60c.png)
If you have further questions don't hesitate to ask. I'd be grateful if you could look into it!

**Comment by DanielWinks** [comment]
Sorry it took a bit to look into this.

What values do you see for the moisture sensor? Is it binary 0/1? 0-100? 0-1 decimal numbers?

**Comment by sbbe** [comment]
Hey, no worries! I believe the value ranges from 0-100 with float numbers

**Comment by DanielWinks** [comment]
Just pushed some updates that should hopefully add support for your WH51. I don't actually have one of these devices to test with (tho I suppose I can just publish a few messages on MQTT to mock it).

Let me know if it's working for you. I updated the documentation to cover adding a moisture sensor and added an example for how to add a WH51, since it uses just a single 'id' and not id+channel. You'll want to put your 'id' value in for the 'uid' key in the config.

**Comment by DanielWinks** [comment]
Fixed with https://github.com/DanielWinks/HassOS-Addons/commit/f1e8f3c040398a6c7cc3006dc03117d1e2db1f03
