### ISSUE TITLE
Adding Fineoffset WH65B

### ISSUE THREAD

**Issue by revilo951** [DanielWinks/HassOS-Addons#16]
Trying to add this weather station. I've added it as a "temp_hum_c" device, and that's working, but that's missing a bunch of info.

Screenshot of MQTT Exporer below. Please let me know if there's anything I can do to help/test etc.

![image](https://user-images.githubusercontent.com/13210587/207284703-5cf483e0-e7f9-4809-a4b6-2f2529f97b48.png)

**Comment by DanielWinks** [comment]
I don't have anything with wind, rain, UV, and light personally. So I haven't added them, because I don't know what topics they use.

I should have some time around the holidays off work that I can add support for them. It'll be a few weeks, but I'll get this put in.

Thanks for the screenshot, that should be all I need to add them.

**Comment by revilo951** [comment]
Awesome, just whenever you get time man. Thanks for such a handy HA addon!

**Comment by DanielWinks** [comment]
Closing this as I am no longer maintaining this add-on (I've moved my home automation to Hubitat and no longer use Home Assistant).
