### ISSUE TITLE
"Exec format error" on installation of rtl_433

### ISSUE THREAD

**Issue by Triberg** [DanielWinks/HassOS-Addons#3]
I tried installing this on HA, but when I start the addon, I just see this line flooding my logs:
```
./run: line 63: /usr/local/bin/rtl_433: cannot execute binary file: Exec format error
```

HA information:
Home Assistant OS 6.3
supervisor-2021.09.0
core-2021.9.5
OS version 5.10.17-v7

**Comment by DanielWinks** [comment]
That's quite odd. That's the error you'd get when trying to run a Arm binary on an x86 CPU or vice versa. Sometimes you'll see it with multi-arch Docker images, where Docker is dumb and runs the wrong thing... but that's not the case here, since HA add-ons don't use multi-arch, they have specific images built for each arch.

What hardware are you running HA on?

**Comment by Triberg** [comment]
I'm on armv7l, it's a Pi 3B+

**Comment by DanielWinks** [comment]
The build for that arch looks fine, as does the image on Docker Hub. I'll have to spin up one of my old Pi 3 to test it and see why it's pulling the wrong image, or why it's building the wrong exec format. I've got a bit going on for the next week or two, so sadly it'll be a bit before I can look more. I think it might be an issue with the container being used with the build.

**Comment by DanielWinks** [comment]
I changed the Dockerfile to use an arch-specific builder. Can you test out the latest version and let me know if that resolved the exec error?

**Comment by Triberg** [comment]
Yes, that resolves the error. Thank you!
